---

- name: Update security for all servers
  hosts: all
  roles:
    - role: patch_security

- name: Setup backend server
  hosts: backend
  roles:
    - role: setup_java
    - role: setup_python

- name: Setup frontend
  hosts: frontend
  roles:
    - role: setup_python
    - role: setup_apache
