---

- name: Ensure security packages are installed
  yum:
    security: yes
    state: latest

- name: Setup motd
  become: true
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644