all:

  # hosts definition
  hosts:
    bta_contract01:
      ansible_port: 2222
      ansible_host: localhost
      ansible_user: root
      ansible_password: passw0rd
    bta_contract02:
      ansible_port: 2223
      ansible_host: localhost
      ansible_user: root
      ansible_password: passw0rd
    bta_contract03:
      ansible_port: 2224
      ansible_host: localhost
      ansible_user: root
      ansible_password: passw0rd
    bta_alert01:
      ansible_port: 2225
      ansible_host: localhost
      ansible_user: root
      ansible_password: passw0rd
    bta_alert02:
      ansible_port: 2226
      ansible_host: localhost
      ansible_user: root
      ansible_password: passw0rd
    bta_admin01:
      ansible_port: 2227
      ansible_host: localhost
      ansible_user: root
      ansible_password: passw0rd

  # groups definition
  children:
    bta_contract:
      hosts:
        bta_contract01:
        bta_contract02:
        bta_contract03:
    bta_alert:
      hosts:
        bta_alert01:
        bta_alert02:
    bta_admin:
      hosts:
        bta_admin01:
  
  # group of groups
    backend:
      children:
        bta_contract:
        bta_alert:
    frontend:
      children:
        bta_admin: